# Generated by Django 5.0.2 on 2024-02-26 11:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0002_alter_post_content"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="likes",
        ),
    ]
