# Generated by Django 5.0.2 on 2024-03-06 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("page", "0003_page_owner_group_id_alter_page_user_id"),
        ("post", "0003_remove_post_likes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="page",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="page.page",
            ),
        ),
    ]
