# Generated by Django 5.0.2 on 2024-03-06 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0004_alter_post_page"),
    ]

    operations = [
        migrations.AlterField(
            model_name="like",
            name="post_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes",
                to="post.post",
            ),
        ),
    ]
