# Generated by Django 5.0.2 on 2024-03-12 14:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0005_alter_like_post_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="like",
            old_name="post_id",
            new_name="post",
        ),
    ]
