FROM python:3.12

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /usr/src/app

# Copy requirements files and install dependencies
COPY requirements.txt /usr/src/app/
RUN pip install --no-cache-dir -r requirements.txt

# Copy all files from the innoter directory to the main directory
COPY . /usr/src/app

WORKDIR /usr/src/app/innoter
