services:
  mysql:
    image: mysql:8.2.0
    command: --default-authentication-plugin=caching_sha2_password
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - '${MYSQL_PORT}:3306'
    init: true
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "${MYSQL_HOST}", "-u", "${MYSQL_USER}", "-p${MYSQL_PASSWORD}"]
      timeout: 5s
      retries: 5
      start_period: 5s
    networks:
      - innoter-network
  celery:
    container_name: celery
    build:
      context: .
    restart: always
    command: sh scripts/entry_celery.sh
    env_file:
      - .dev.env
    networks:
      - user-management-service_app-network
      - innoter-network
    healthcheck:
      test: [ "CMD", "celery", "inspect", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 3
  innoter-app:
    container_name: innoter-app
    build:
      context: .
    command: sh scripts/entry.sh
    env_file:
      - .dev.env
    volumes:
      - .:/usr/src/app
    ports:
      - ${APP_PORT}:8000
    init: true
    depends_on:
      mysql:
        condition: service_healthy
      celery:
        condition: service_healthy
    networks:
      - innoter-network

volumes:
  mysql-data:
    driver: local
networks:
  user-management-service_app-network:
    external: true
  innoter-network:
    driver: bridge
