# Generated by Django 5.0.2 on 2024-02-26 11:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("page", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="page",
            name="followers",
        ),
    ]
