# Generated by Django 5.0.2 on 2024-03-05 15:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("page", "0002_remove_page_followers"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="owner_group_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="page",
            name="user_id",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
