# Generated by Django 5.0.2 on 2024-03-12 14:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("page", "0003_page_owner_group_id_alter_page_user_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="follower",
            old_name="page_id",
            new_name="page",
        ),
    ]
